name:    yesodnix
version:             0.1.0.0
license:             BSD3

extra-source-files:
- readme.md


dependencies:
- base >= 4.7 && < 5
- yesod
- persistent-postgresql
- resource-pool
- monad-logger
- text
- aeson

default-extensions:
- TypeFamilies
- DerivingStrategies
- DeriveGeneric
- DeriveAnyClass
- FlexibleInstances
- UndecidableInstances
- OverloadedStrings
- GADTs
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- DataKinds
- MultiParamTypeClasses
- RecordWildCards

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  yesodnix:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesodnix